// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX8bjOe-vlrmKZQx_MwXo113iyLVent3s',
    appId: '1:231340507698:web:08a4efcaeaaca0c6b2322b',
    messagingSenderId: '231340507698',
    projectId: 'livenotes-30d87',
    authDomain: 'livenotes-30d87.firebaseapp.com',
    storageBucket: 'livenotes-30d87.firebasestorage.app',
    measurementId: 'G-CXTZPM5P1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHJ3rOEJoM2sGUtQA2uOEyuBHl7ZyTdLg',
    appId: '1:231340507698:android:136c17f182ab2fb3b2322b',
    messagingSenderId: '231340507698',
    projectId: 'livenotes-30d87',
    storageBucket: 'livenotes-30d87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbENuIkAxwPEvZm3j5BdbqF9sBj2r5I-g',
    appId: '1:231340507698:ios:e2a54d9addaafa29b2322b',
    messagingSenderId: '231340507698',
    projectId: 'livenotes-30d87',
    storageBucket: 'livenotes-30d87.firebasestorage.app',
    iosBundleId: 'com.example.liveNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbENuIkAxwPEvZm3j5BdbqF9sBj2r5I-g',
    appId: '1:231340507698:ios:e2a54d9addaafa29b2322b',
    messagingSenderId: '231340507698',
    projectId: 'livenotes-30d87',
    storageBucket: 'livenotes-30d87.firebasestorage.app',
    iosBundleId: 'com.example.liveNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX8bjOe-vlrmKZQx_MwXo113iyLVent3s',
    appId: '1:231340507698:web:6bdcd88ce7750ee5b2322b',
    messagingSenderId: '231340507698',
    projectId: 'livenotes-30d87',
    authDomain: 'livenotes-30d87.firebaseapp.com',
    storageBucket: 'livenotes-30d87.firebasestorage.app',
    measurementId: 'G-P7QQG2EP50',
  );
}
